// settings.gradle (Groovy形式)

// プラグインの管理設定
pluginManagement {
    // プラグインを探しに行く「倉庫」のリスト
    repositories {
        // Googleのプラグインが置いてある倉庫
        google()
        // 一般的なライブラリやプラグインが置いてある倉庫
        mavenCentral()
        // Gradle公式のプラグインが置いてある倉庫
        gradlePluginPortal()
    }
}

// ライブラリの管理設定
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    // ライブラリを探しに行く「倉庫」のリスト
    repositories {
        google()
        mavenCentral()
    }
}

// プロジェクトの基本情報
rootProject.name = "DisasterMailRelay"
// このプロジェクトに含まれるモジュール（部品）
include ':mobile'
